spring:
  application:
    name: finalProject
  config:
    import: optional:env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmatedb
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mail: #JavaMailSender
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt: #JWT Config
  signerKey: ${JWT_SIGNER_KEY}
  expiration: 180
  expirationRefreshToken: 604800
  revoke: true

frontend: #Frontend Domain
  domain: https://abcd.com

app: #App config
  config:
    filter:
      limitTimeWindow: 60000
      maxRequest: 100
    file:
      max-size: 5242880
    paths:
      public-dir: public
      upload-dir: upload
      common-images-dir: images
      images-dir: images
      logos-dir: logos
      avatars-dir: avatars
      articles-dir: articles
      pdfs-dir: pdfs
      audios-dir: audios
      docs-dir: docs
      videos-dir: videos
      categories-dir: categories
